services:
  pg:
    image: bitnami/postgresql:latest
    container_name: brevly-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - "./docker:/docker-entrypoint-initdb.d"
      - db:/var/lib/postgresql/data
    networks:
      - brevly

  app:
    build: .
    container_name: brevly-app
    ports:
      - 3333:${PORT}
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
      - CLOUDFLARE_BUCKET=${CLOUDFLARE_BUCKET}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_PUBLIC_URL=${CLOUDFLARE_PUBLIC_URL}
    networks:
      - brevly

volumes:
  db:

networks:
  brevly:
    driver: bridge
